spring:
  application:
    name: content-mng
#  neo4j:
#    uri: bolt://localhost:7687
#    authentication:
#      username: neo4j
#      password: secret
  #  data:
#    neo4j:




bolt:
  enabled: true